spring.application.name=social_interest


spring.data.mongodb.interests.uri=${INTEREST_URI}


spring.data.mongodb.reels.uri=${REEL_URI}


spring.jwt.secret=${JWT_SECRET}


secret.service=${SERVICE_SECRET}